# Generated by Django 5.2.12 on 2026-03-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("citations", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="done",
                        max_length=20,
                    ),
                ),
                ("error_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="UploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "stored_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploaded_excels/"
                    ),
                ),
                ("file_hash", models.CharField(max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("column_count", models.PositiveIntegerField(default=0)),
                ("columns_json", models.JSONField(blank=True, default=list)),
                (
                    "null_strategy",
                    models.CharField(
                        choices=[
                            ("none", "No Fill"),
                            ("frontfill", "Forward Fill"),
                            ("backfill", "Backward Fill"),
                            ("back_forward_fill", "Forward + Backward Fill"),
                            ("mean_fill", "Mean Fill (numeric)"),
                            ("zero_fill", "Zero Fill"),
                        ],
                        default="none",
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("file_deleted", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTraceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_index", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "event_kind",
                    models.CharField(
                        choices=[("trace", "Trace"), ("status", "Status")],
                        default="trace",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_events",
                        to="ai_analysis.chatmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="upload_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="ai_analysis.uploadrecord",
            ),
        ),
    ]
