# Generated by Django 5.2.12 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_analysis", "0002_chatsession_chatmessage_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuntimeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ollama_base_url", models.CharField(default="", max_length=255)),
                ("ollama_qa_model", models.CharField(default="", max_length=120)),
                ("ollama_chat_model", models.CharField(default="", max_length=120)),
                ("ollama_embed_model", models.CharField(default="", max_length=120)),
                ("custom_prompt", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
